version: '3.8'

services:
  backend:
    image: tipo-cambio
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tipo-cambio
    restart: always
    ports:
      - 8080:8080
    networks:
      lan:
        aliases:
          - backend_host
networks:
  lan:
    name: lan_net
    driver: bridge